name: Build and Release Flutter App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.35.1"

      - name: Install Dependencies
        run: flutter pub get

      - name: Decode Android Keystore
        run: |
          echo "Checking if KEYSTORE_FILE_BASE64 secret exists..."
          if [ -z "${{ secrets.KEYSTORE_FILE_BASE64 }}" ]; then
            echo "ERROR: KEYSTORE_FILE_BASE64 secret is empty!"
            exit 1
          fi
          echo "Decoding keystore..."
          echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 -d > android/app/keystore.jks
          echo "Keystore size: $(stat -c%s android/app/keystore.jks) bytes"
          if [ ! -s android/app/keystore.jks ]; then
            echo "ERROR: Keystore file is empty after decoding!"
            echo "First 100 chars of base64 secret: ${KEYSTORE_FILE_BASE64:0:100}"
            exit 1
          fi
        env:
          KEYSTORE_FILE_BASE64: ${{ secrets.KEYSTORE_FILE_BASE64 }}

      - name: Create key.properties
        run: |
          cat << EOF > android/key.properties
          storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          storeFile=../app/keystore.jks
          EOF
          echo "=== key.properties content ==="
          cat android/key.properties
          echo "=== end key.properties ==="

      - name: Verify Keystore
        run: |
          echo "=== Keystore Information ==="
          ls -la android/app/keystore.jks
          echo "File type: $(file android/app/keystore.jks)"
          echo "=== Testing keystore ==="
          if keytool -list -keystore android/app/keystore.jks -storepass "${{ secrets.ANDROID_STORE_PASSWORD }}" -v; then
            echo "✅ Keystore verification SUCCESS!"
          else
            echo "❌ Keystore verification FAILED!"
            echo "Keystore content (first 50 bytes as hex):"
            xxd -l 50 android/app/keystore.jks || echo "Could not read keystore content"
            exit 1
          fi

      - name: Build Android App Bundle
        run: flutter build appbundle --release

      - name: Decode Google Play Service Account
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.PLAY_STORE_CREDENTIALS }}" | base64 -d > service-account.json

      - name: Deploy to Google Play Store (Closed Testing)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service-account.json
          packageName: com.gabrielfvdev.cripto_app
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: alpha
          status: completed
