name: Build and Release Flutter App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.24.0"

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Analysis and Tests
        run: |
          flutter analyze
          flutter test

      - name: Decode Android Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/keystore.jks

      - name: Create key.properties
        run: |
          cat << EOF > android/key.properties
          storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          storeFile=../app/keystore.jks
          EOF

      - name: Verify Keystore
        run: |
          ls -la android/app/keystore.jks
          keytool -list -keystore android/app/keystore.jks -storepass "${{ secrets.ANDROID_STORE_PASSWORD }}" || echo "Keystore verification failed"

      - name: Build Android App Bundle
        run: flutter build appbundle --release

      - name: Decode Google Play Service Account
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_BASE64 }}" | base64 -d > service-account.json

      - name: Deploy to Google Play Store (Closed Testing)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service-account.json
          packageName: com.gabrielfvdev.cripto_app
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: alpha
          status: completed
